### ISSUE TITLE
Personalize README.md

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/munich#1]
We've provided a basic readme for you, but you should personalize it for your own
chapter's needs. You might want to:

- adjust the welcome section
- add some regional flair (like Mumbai's multi-language welcome or Seattle's emojis 🌲🗻☔️)
- include additional contact info for organizers (email, Twitter, etc.)
- mention related Meetup groups that will be hosting your ProtoSchool events
- request help planning upcoming events
- call for co-organizers to join you
- add calls to action (see issue #2)

**Comment by stefanhans** [comment]
Sometimes a do wake up in the middle of the night with some ideas. So it was this night. Please have a look at the readme. Do not hesitate with critics and feedback.

**Comment by stefanhans** [comment]
If you have no objections, I will close the issue.
