### ISSUE TITLE
Review Code of Conduct

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/munich#3]
We've provided a draft Code of Conduct for you that includes the contact information you provided for reporting purposes. Please ensure that these contact details are correct.

Please ensure that all chapter organizers have reviewed the CoC thoroughly and are comfortable enforcing it.

(This will need to be done before we can list your chapter on our website.)

**Comment by stefanhans** [comment]
CoC reviewed, email checked. 

@rklaehn Could you please review the CoC, as well.

**Comment by stefanhans** [comment]
@rklaehn If you have no objections, you can close the issue.
