### ISSUE TITLE
Add your chapter to our listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/munich#4]
Once issues #1, #2, and #3 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) by opening a pull request to have your chapter included in the [list of ProtoSchool chapters](https://proto.school/#/chapters).

Please be sure to include the `repo` field so that your listing will link to this chapter repo. Should you decide that you'd like your listing to go to a website instead (now or in the future), you can add an additional `website` field with the appropriate URL, which will update the link.

**Comment by terichadbourne** [comment]
@stefanhans @rklaehn Just popping in with a reminder that your chapter isn't yet listed on our main  website, although you've done a ton to prepare your repo. Please let me know if you have any questions about the process of getting it added.

**Comment by stefanhans** [comment]
I was waiting for @rklaehn to check the CoC. I will close the issue and
list the chapter today.

**Comment by stefanhans** [comment]
PR committed and all checks passed
